### ISSUE TITLE
Create axios adapter

### ISSUE THREAD

**Issue by Kelin2025** [apicase/apicase-core#2]
Adapter will available as `apicase-adapter-axios` package.
More info later

**Comment by Kelin2025** [comment]
Axios is useless

**Comment by ITEANJD** [comment]
why is Axios useless? 
could you point me to some articles explaining it?

**Comment by Kelin2025** [comment]
@ITEANJD axios is just a "promisify" with some sugar for XHR. Apicase provides full-featured API layer and fits into axios size. It's much more flexible, extendable and doesn't need any additional wrappers
